'use strict';
const $=id=>document.getElementById(id),form=$('controls'),E=SimEngine;
const pct=(v,d=1)=>(v*100).toFixed(d)+'%',money=v=>'$'+(v/1e6).toLocaleString(undefined,{maximumFractionDigits:1})+'m';
const categories=['no_shortfall_ever','injection_then_recovery','psa_covered_no_injection','shortfall_every_checkpoint'];
let result=null,selected=9,worker=null,workerUrl=null,running=false;
const percentKeys=['psa0_pct_of_pa','required_psa_pct','shortfall_coverage','guarantee_rate','beir_rate','risk_free_rate','guaranteed_pct_start','profit_split_shareholder','bel_growth_rate','mcl_growth_rate'];
function readConfig(){const c={};for(const [k,v] of new FormData(form)){c[k]=k==='method'?v:k==='periodic_profit_check'?v==='true':v===''?null:Number(v);if(percentKeys.includes(k)&&c[k]!==null)c[k]/=100;}c.pa0*=1e9;return E.config(c);}
function syncControls(){form.elements.block_size_months.disabled=form.elements.method.value!=='block';form.elements.bonus_freq_months.disabled=form.elements.periodic_profit_check.value==='false';$('policyholder-share').textContent='Policyholder share: '+(100-Number(form.elements.profit_split_shareholder.value)).toFixed(2).replace(/\.00$/,'')+'% (retained in PA).';}
form.addEventListener('input',()=>{syncControls();if(result&&!running)$('run-status').textContent='Inputs changed. Run again to update results; displayed results retain their previous settings.';});
form.addEventListener('reset',()=>setTimeout(()=>{syncControls();$('run-status').textContent='Defaults restored. Run to update results.';},0));
function save(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportRows(rows){return rows.map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k.replace(/^TM_/, 'Cap_').replace('shareholder_cut_applied_this_month','Holder_Profit_Share').replace('shareholder_cut_decided','Holder_Profit_Share_decided'),v])));}
function csv(rows){const keys=Object.keys(rows[0]||{}),quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return new Blob(['\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});}
function simpleTable(rows,cols){return '<table><thead><tr>'+cols.map(c=>'<th>'+c[1]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+(c[2]?c[2](r[c[0]]):r[c[0]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function stop(){worker?.terminate();worker=null;if(workerUrl)URL.revokeObjectURL(workerUrl);workerUrl=null;running=false;for(const el of form.elements)el.disabled=false;syncControls();$('cancel').hidden=true;}
form.addEventListener('submit',event=>{event.preventDefault();if(running)return;try{
  const c=readConfig();running=true;for(const el of form.elements)el.disabled=true;$('cancel').disabled=false;$('cancel').hidden=false;$('run-status').className='';$('run-status').textContent='Generating shared asset returns…';
  const source=E.workerSource+`self.onmessage=function(e){try{const c=SimEngine.config(e.data.c),hist=e.data.hist,raw=SimEngine.generate(hist,c),scenarios=[];for(const eq of SimEngine.equityWeights)for(const b of SimEngine.bondShares){scenarios.push(SimEngine.scenario(raw,eq,b,c));self.postMessage({progress:scenarios.length});}self.postMessage({done:true,c,scenarios});}catch(e){self.postMessage({error:e.message});}};`;
  workerUrl=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));worker=new Worker(workerUrl);
  worker.onmessage=event=>{const d=event.data;if(d.error){stop();$('run-status').textContent=d.error;$('run-status').className='error';}else if(d.done){result={c:d.c,scenarios:d.scenarios};stop();render();$('run-status').textContent='Complete. All 20 allocations simulated.';}else $('run-status').textContent='Simulating allocation '+d.progress+' of 20…';};
  worker.onerror=event=>{stop();$('run-status').className='error';$('run-status').textContent='Simulation could not run: '+(event.message||'browser blocked the worker. Serve this folder over localhost or GitHub Pages.');};
  worker.postMessage({c,hist:HISTORICAL_DATA.returns});
}catch(e){stop();$('run-status').className='error';$('run-status').textContent=e.message;}});
$('cancel').onclick=()=>{stop();$('run-status').textContent='Cancelled. Any previous results remain unchanged.';};
function histogram(id,values,threshold,label){const width=570,height=300,left=52,right=20,top=20,bottom=50,mean=E.mean(values);let lo=Math.min(threshold,mean),hi=Math.max(threshold,mean);for(const v of values){lo=Math.min(lo,v);hi=Math.max(hi,v);}let span=hi-lo||.02;lo-=span*.03;hi+=span*.03;span=hi-lo;const bins=Array(50).fill(0);for(const v of values)bins[Math.min(49,Math.floor((v-lo)/span*50))]++;const max=Math.max(...bins),x=v=>left+(v-lo)/span*(width-left-right),y=v=>height-bottom-v/max*(height-top-bottom),bw=(width-left-right)/50;
  let svg='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+label+' distribution"><title>'+label+' distribution; mean '+pct(mean)+'; guarantee '+pct(threshold)+'</title>';
  for(let i=0;i<=4;i++){const v=max*i/4;svg+='<line x1="'+left+'" x2="'+(width-right)+'" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#e5ebed"/><text x="'+(left-8)+'" y="'+(y(v)+4)+'" text-anchor="end">'+Math.round(v)+'</text>';}
  bins.forEach((v,i)=>svg+='<rect x="'+(left+i*bw)+'" y="'+y(v)+'" width="'+Math.max(1,bw-1)+'" height="'+(height-bottom-y(v))+'" fill="#318b83" fill-opacity="0.40"><title>'+pct(lo+i/50*span)+' to '+pct(lo+(i+1)/50*span)+': '+v+' paths</title></rect>');
  for(let i=0;i<=5;i++){const v=lo+i/5*span;svg+='<text x="'+x(v)+'" y="'+(height-bottom+22)+'" text-anchor="middle">'+pct(v,0)+'</text>';}
  for(const [v,color,dash] of [[threshold,'#a95a12','6 4'],[mean,'#17252b','0']])svg+='<line x1="'+x(v)+'" x2="'+x(v)+'" y1="'+top+'" y2="'+(height-bottom)+'" stroke="'+color+'" stroke-width="2" stroke-dasharray="'+dash+'"/>';
  svg+='<text x="'+left+'" y="295">Count · teal bars</text><text x="240" y="295">Amber dashed: guarantee</text><text x="440" y="295">Dark: mean</text></svg>';
  $(id).innerHTML=svg;
}
function render(){const {c,scenarios}=result;$('results').hidden=false;$('run-meta').textContent=`${c.method==='gbm'?'Correlated GBM':c.block_size_months+'-month block bootstrap'} · ${c.n_years} years + 1 settlement month · ${c.n_sims.toLocaleString()} paths × 20 allocations · seed ${c.random_seed} · ${c.periodic_profit_check?'checks every '+c.bonus_freq_months+' months + final':'final checkpoint only'}`;
  const cagrs=scenarios.flatMap(s=>s.cagrs),terminal=scenarios.flatMap(s=>s.terminals),below=cagrs.filter(v=>v<c.guarantee_rate).length/cagrs.length;
  $('metrics').innerHTML=[[pct(E.mean(cagrs)),'Pooled mean CAGR'],[pct(below),'% of paths that fell below the guaranteed return'],[pct(E.mean(scenarios.map(s=>s.summary.pct_paths_injection))),'Pooled capital injection probability'],[money(E.mean(scenarios.map(s=>s.summary.mean_injection_amount))),'Pooled mean total capital injection']].map(([v,label])=>'<div class="metric"><strong>'+v+'</strong><span>'+label+'</span></div>').join('');
  $('cagr-caption').textContent=cagrs.length.toLocaleString()+' scenario-path observations · '+pct(below)+' below '+pct(c.guarantee_rate,2)+'. Allocations share return draws.';
  const threshold=Math.pow(1+c.guarantee_rate,c.n_years)-1;$('terminal-caption').textContent=c.n_years+'-year capital-neutral cumulative return · guarantee '+pct(threshold,2)+'.';
  histogram('cagr-chart',cagrs,c.guarantee_rate,'CAGR');histogram('terminal-chart',terminal,threshold,'Terminal return');renderSelection();}
function renderSelection(){const {scenarios}=result;let html='<table class="heat"><thead><tr><th>Equity ↓ / 10Y+ share of bonds →</th>'+E.bondShares.map(v=>'<th>'+pct(v,0)+'</th>').join('')+'</tr></thead><tbody>';
  E.equityWeights.forEach((eq,i)=>{html+='<tr><th>'+pct(eq,0)+'</th>';E.bondShares.forEach((_,j)=>{const index=i*4+j,s=scenarios[index].summary,p=s.pct_paths_injection,color=`hsl(14 66% ${96-p*32}%)`;html+='<td><button data-scenario="'+index+'" class="'+(index===selected?'selected':'')+'" aria-pressed="'+(index===selected)+'" style="background:'+color+'"><strong>'+pct(s.mean_CAGR)+'</strong><small>Cap injection '+pct(p)+' · No shortfall '+pct(s.pct_paths_no_shortfall,0)+'</small><small>Below guarantee '+pct(s.pct_paths_below_guarantee,0)+'</small></button></td>';});html+='</tr>';});$('heatmap').innerHTML=html+'</tbody></table>';renderTable();renderDetail();}
function renderTable(){const sort=$('sort').value,rows=result.scenarios.map((s,i)=>({...s.summary,i})).sort((a,b)=>(sort==='mean_CAGR'?-1:1)*(a[sort]-b[sort]));const cols=[['equity_weight','Equity',pct],['bond_10y_plus_share','10Y+ / bonds',pct],['mean_CAGR','Mean CAGR',pct],['median_CAGR','Median CAGR',pct],['p05_CAGR','P05 CAGR',pct],['p95_CAGR','P95 CAGR',pct],['pct_paths_below_guarantee','Below guarantee',pct],['pct_paths_no_shortfall','No shortfall',pct],['pct_paths_psa_only','PSA-only event',pct],['pct_paths_injection','Cap injection',pct],['mean_injection_amount','Mean injection',money],['mean_cumulative_uncovered_shortfall','Mean cumulative uncovered',money]];
  $('scenario-table').innerHTML='<table><thead><tr><th>Explore</th>'+cols.map(x=>'<th>'+x[1]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr class="'+(r.i===selected?'selected':'')+'"><td><button data-scenario="'+r.i+'">'+(r.i===selected?'Selected':'View')+'</button></td>'+cols.map(x=>'<td>'+x[2](r[x[0]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
document.addEventListener('click',event=>{const b=event.target.closest('[data-scenario]');if(b){selected=Number(b.dataset.scenario);renderSelection();}});$('sort').onchange=renderTable;
function renderDetail(){const s=result.scenarios[selected],c=result.c,a=s.summary;$('detail-title').textContent=pct(a.equity_weight,0)+' equity · '+pct(a.bond_10y_plus_share,0)+' of bonds in 10Y+';
  const n=c.n_years*12+1,benchmark=Array.from({length:n+1},(_,i)=>Math.pow(1+c.guarantee_rate,i/12)),paths=s.sample.map(p=>[1,...p]);let lo=1,hi=1;for(const p of [...paths,benchmark])for(const v of p){lo=Math.min(lo,v);hi=Math.max(hi,v);}const pad=(hi-lo)*.05||.05;lo-=pad;hi+=pad;const w=1100,h=340,x=t=>60+t/n*1015,y=v=>290-(v-lo)/(hi-lo)*265;
  let svg='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Policy asset wealth paths including capital events"><title>Policy assets normalized to initial value, including settlement month</title>';
  for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;svg+='<line x1="60" x2="1075" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#e1e8eb"/><text x="50" y="'+(y(v)+4)+'" text-anchor="end">'+v.toFixed(2)+'</text>';}
  for(let t=1;t<=n-1;t++)if(t===n-1||(c.periodic_profit_check&&t%c.bonus_freq_months===0))svg+='<line x1="'+x(t)+'" x2="'+x(t)+'" y1="25" y2="290" stroke="#a2afb4" stroke-dasharray="4 5"/>';
  for(const p of paths)svg+='<polyline points="'+p.map((v,i)=>x(i)+','+y(v)).join(' ')+'" fill="none" stroke="#28877f" stroke-opacity=".35" stroke-width="1.5"/>';
  svg+='<polyline points="'+benchmark.map((v,i)=>x(i)+','+y(v)).join(' ')+'" fill="none" stroke="#b87225" stroke-width="2.5"/>';
  for(let i=0;i<=5;i++){const t=Math.round(n*i/5);svg+='<text x="'+x(t)+'" y="313" text-anchor="middle">'+t+'</text>';}
  $('wealth-chart').innerHTML=svg+'<text x="60" y="337">Month · teal: PA paths · amber: guarantee benchmark</text></svg>';renderExample();}
function renderExample(){const s=result.scenarios[selected],k=Number($('example').value),ex=s.examples[k];$('export-path').disabled=!ex;if(!ex){$('example-note').textContent='No simulation matched this category for this allocation and run. Try more paths or different assumptions.';$('example-table').innerHTML='';return;}
  $('example-note').textContent='Simulation index '+ex.sim_index+' (zero-based). Amber rows: decisions at checkpoints. Green rows: subsequent settlement/reset. Dollar amounts shown in millions; downloads preserve full precision. PL reset driver compares post-capital opening PA with the prior checkpoint’s PV BEL and PV MCL, before monthly growth. Highlighted liability labels flag a value above PA; PA includes ties. A dash means no reset that month. Recovery means no injection at the final checkpoint, not necessarily no shortfall.';
  const cols=[['month','Month',v=>v],['PA','PA',money],['PL','PL',money],['BEL','BEL',money],['MCL','MCL',money],['PA_return','Return',pct],['PSA','PSA',money],['PSA_pct_PA','PSA / PA',pct],['equity_weight','Equity',pct],['bond_3_5y_weight','3–5Y',pct],['bond_10y_plus_weight','10Y+',pct],['profit_at_checkpoint','Profit / (shortfall)',money],['PV_BEL_at_checkpoint','PV BEL',money],['PV_MCL_at_checkpoint','PV MCL',money],['covered_shortfall','Covered',money],['uncovered_shortfall','Uncovered',money],['running_cumulative_uncovered_shortfall','Cumulative uncovered',money],['TM_injection_decided','Cap injection decided',money],['PSA_draw_decided','PSA draw decided',money],['shareholder_cut_decided','Holder Profit Share decided',money],['TM_injection_applied_this_month','Cap injection landed',money],['PSA_draw_applied_this_month','PSA draw landed',money],['shareholder_cut_applied_this_month','Holder Profit Share',money]];
  cols.splice(3,0,['PL_reset_driver','PL reset driver',v=>v==='PA'?v:'<strong class="liability-reset" title="Liability present value exceeds opening PA at this reset">'+v+'</strong>']);
  const shortfallStart=cols.findIndex(x=>x[0]==='covered_shortfall');
  $('example-table').innerHTML='<table class="path-audit"><thead><tr>'+cols.map((x,i)=>i===shortfallStart?'<th colspan="3" scope="colgroup" class="shortfall-group">Shortfall</th>':i===shortfallStart+1||i===shortfallStart+2?'':'<th rowspan="2" scope="col">'+x[1]+'</th>').join('')+'</tr><tr>'+cols.slice(shortfallStart,shortfallStart+3).map(x=>'<th scope="col">'+x[1]+'</th>').join('')+'</tr></thead><tbody>'+ex.rows.map(r=>'<tr class="'+(r.is_checkpoint?'checkpoint':r.PL_reset_before_monthly_drift!==null?'settlement':'')+'">'+cols.map(x=>'<td>'+(r[x[0]]===null?'—':x[2](r[x[0]]))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
$('example').onchange=renderExample;
$('export-summary').onclick=()=>save('par_fund_scenarios.csv',csv(result.scenarios.map(s=>s.summary)));
$('export-path').onclick=()=>{const k=Number($('example').value);save(categories[k]+'.csv',csv(exportRows(result.scenarios[selected].examples[k].rows)));};
$('export-excel').onclick=()=>{const s=result.scenarios[selected],info={...result.c,...s.summary,history_start:HISTORICAL_DATA.dates[0],history_end:HISTORICAL_DATA.dates.at(-1),history_months:HISTORICAL_DATA.returns.length,note:'JavaScript RNG differs from NumPy. Capital lands next month; PL resets before monthly drift. PV uses a flat one-year exponent. Final extra month excluded from CAGR. Cumulative uncovered is reporting only.'};categories.forEach((k,i)=>info[k+'_sim_index']=s.examples[i]?.sim_index??'NOT FOUND');save('example_paths.xlsx',makeWorkbook([{name:'scenario_info',rows:[info]},...categories.map((name,i)=>({name,rows:exportRows(s.examples[i]?.rows||[{note:'No simulation matched this category.'}])}))]));};
try{const stats=E.stats(HISTORICAL_DATA.returns);$('data-status').textContent=HISTORICAL_DATA.returns.length+' aligned monthly observations · '+HISTORICAL_DATA.dates[0]+' to '+HISTORICAL_DATA.dates.at(-1)+' · '+HISTORICAL_DATA.dropped+' merged row(s) removed for missing returns';$('asset-table').innerHTML=simpleTable(stats.assets,[['asset','Asset'],['monthly_mean','Monthly mean',v=>pct(v,3)],['monthly_vol','Monthly volatility',v=>pct(v,3)],['annualized_mean','Annualized mean',v=>pct(v,2)],['annualized_vol','Annualized volatility',v=>pct(v,2)]]);$('export-stats').onclick=()=>save('asset_return_vol_summary.csv',csv(stats.assets));syncControls();}catch(e){$('data-status').textContent=e.message;$('run').disabled=true;}
